add comments to unintegrated pages
ProteinsWebTeam/pronto pull request #44
Opened 2021-11-10 09:08 UTC by typhainepl

2021-11-12 12:44 UTC, matthiasblum commented on pronto/api/database.py
> +            continue
There is a more efficient way to retrieve the latest comment for each signature: 

https://github.com/ProteinsWebTeam/pronto/blob/c3893871a15c08ad7517049f166efe2a0b61702f/pronto/api/database.py#L117-L147

Alternatively, instead of storing only the most recent comment in the `comments` dict, we can store all of them. This way, we do not have the build the `num_comments` dict (and when generating the final JSON object, we can use the most recent comment from the `comments` dict).

2021-11-12 13:10 UTC, matthiasblum requested changes
There a few minor things to address, but it looks very nice overall. Thank you!

2021-11-12 13:10 UTC, matthiasblum commented on pronto/templates/database/unintegrated.html
> +        .ui.form>.inline.fields>label {
Not that it's important, but are these changes due to an automated formatting tool?

2021-11-12 13:10 UTC, matthiasblum commented on pronto/templates/database/unintegrated.html
> +                <div class="thirteen wide column">
There is not much space for the comments on the right side of the page. Can you check if it looks better with a `twelve wide column` (for the table) and `four wide column` (for the comments)?

2021-11-12 14:45 UTC, typhainepl commented on pronto/templates/database/unintegrated.html
> +        .ui.form>.inline.fields>label {
yes they are from the formatting using black.

2021-11-12 14:47 UTC, typhainepl commented on pronto/templates/database/unintegrated.html
> +                <div class="thirteen wide column">
I tried the `twelve wide column` and `four wide column` option, but the `twelve wide column` wasn't large enough to include all the columns and the comments part was overlapping.

2021-11-12 14:49 UTC, typhainepl commented on pronto/static/js/database/signatures.js
> +        document.querySelector('#signatures thread input'),
oups sorry, I've reverted it

2021-11-12 16:20 UTC, typhainepl commented on pronto/api/database.py
> +            continue
I've updated the requests

2021-11-22 16:34 UTC, merged

2021-11-22 16:34 UTC, matthiasblum commented
Looks great, thanks!