add spurious protein info
ProteinsWebTeam/pronto pull request #47
Opened 2022-04-01 17:04 UTC by typhainepl

2022-04-28 12:27 UTC, matthiasblum requested changes
Well done!

There are a couple of issues, but they should be easy to address.

2022-04-28 14:09 UTC, typhainepl commented on pronto/static/js/ui/proteins.js
> +            </div > `;
For the first part, I thought about it, but I also wanted the info to be visible when looking at the overlapping page, and I thought having both on the protein page will be duplicating information.

Second part, the text isn't 100% red atm, I had chosen another colour when playing around with the message box. I will change it to use `ui red text`. I didn't know which css to use, I'll be careful in the future

2022-04-28 15:11 UTC, typhainepl commented on pronto/api/protein.py
> +            WHERE database_id=16) m ON m.protein_acc=p.accession
done

2022-04-28 15:11 UTC, typhainepl commented on pronto/static/js/ui/proteins.js
> +            html += `< rect x = "${x}" y = "15" width = "${w}" height = "10" rx = "1" ry = "1" style = "fill: ${signature.color};" />
resolved

2022-04-29 10:53 UTC, matthiasblum commented on pronto/static/js/ui/proteins.js
> +            </div > `;
I don't think there would be duplication of information as `protein.js` is for the protein page, and `signatures.js` is for the overlapping proteins page. But it is fine as it is, the information is there.

Thank you for reverting the `semantic.css` file. It's true that without a proper developer documentation, you couldn't know which file to edit. Sorry about that. :sweat_smile:

2022-04-29 10:56 UTC, matthiasblum requested changes
Almost there! Only one tiny change to make, and it's only because I am being picky. ;)

2022-04-29 10:56 UTC, matthiasblum commented on pronto/api/protein.py
> +    is_spurious = True if row[0] != 0 else False
As `row[0] != 0` returns a boolean, you can directly do:
```
is_spurious = row[0] != 0
```

2022-05-03 13:38 UTC, matthiasblum approved these changes
Good to go. Thank you!

2022-05-04 08:59 UTC, merged