add weekly sanity checks
ProteinsWebTeam/pronto pull request #50
Opened 2022-06-01 14:43 UTC by typhainepl

The list of checks added can be found in JIRA: https://www.ebi.ac.uk/panda/jira/browse/IBU-9881

2022-06-22 14:05 UTC, matthiasblum requested changes
Thank you!

I made a few comments. Not all have to be addressed, and some may require a discussion with curators and Alex.

I think the long checks are long/slow because you are fetching records from `signature2protein`. I have suggested ways to use already processed data which should make the checks must faster. If it's the case, we can drop the "Use long checks" option on the website and run all checks all the time.

2022-06-22 14:05 UTC, matthiasblum commented on pronto/api/checks/long_check.py
> +    return errors
To avoid having the get signatures from `signature2protein` (which is slow), you can get signatures that only match fragments as follows (in PostgreSQL):

```SQL
SELECT accession
FROM signature
WHERE num_sequences > 0
AND num_complete_sequences = 0
```

Then, if there are signatures in this case, check whether they are integrated.

2022-06-23 10:08 UTC, matthiasblum commented on pronto/api/checks/__init__.py
> +    if run_all_checks == "true":
That's because the value is not converted to a boolean. If you look at [my other comment](https://github.com/ProteinsWebTeam/pronto/pull/50#discussion_r903620886), `run_all_checks` will be a boolean.

2022-06-23 10:40 UTC, typhainepl commented on pronto/api/checks/go_terms.py
> +    return cur.fetchall()
If `ENTRY_ACCPAIR` and `ENTRY_DELETED` are not used any more, and we have the foreign key, I think we can delete this check indeed.

2022-06-30 14:03 UTC, typhainepl commented on pronto/api/checks/go_terms.py
> +    )
This can't be used for Oracle requests, I've tried something else, let me know if you are happy with it.

2022-06-30 15:11 UTC, typhainepl commented
I have updated the code following your comments. It is much faster than before: all the checks run in about 5 minutes :)

2022-07-01 13:49 UTC, matthiasblum requested changes
Almost there! :muscle: 

The main concern is binding variables. In one comment I have included a link to an case where I use variable binding in a `WHERE <COLUMN> IN (...)` statement. In another comment, there is a link to the `cx_Oracle` documentation on variable binding.

2022-07-01 13:49 UTC, matthiasblum commented on pronto/api/checks/entries.py
> +        errors.append((f"{row[0]}: {row[1]}", f"{row[2]}: {row[3]}"))
Each error is a tuple of two strings indeed. But the first string should be an accession (for InterPro entries and member database signatures) or an identifier (for common annotation blocks) so links are created in the web report. Here, the first string would be something like `IPR000001: D`.

2022-07-01 13:49 UTC, matthiasblum commented on pronto/api/checks/entries.py
> +        SELECT A.PARENT_AC PARENT, B2.ENTRY_TYPE AS PARENT_TYPE, A.ENTRY_AC CHILD, B1.ENTRY_TYPE TYPE
More a comment than an issue: you do not need to give aliases to the selected columns. Aliases are useful within the statement, e.g.

```sql
SELECT ID, CNT
FROM (
  SELECT ID, COUNT(*) AS CNT
  FROM MY_TABLE
)
WHERE CNT > 1;
```

or if you retrieve records as a list of dictionaries instead of a list of lists/tuples.

2022-07-01 13:49 UTC, matthiasblum commented on pronto/api/checks/entries.py
> +        errors.append((f"{row[0]}: {row[1]}", f"{row[2]}: {row[3]}"))
First item of the tuple must be the entry accession. Second item is the description of the error.

2022-07-01 13:49 UTC, matthiasblum commented on pronto/api/checks/entries.py
> +def ck_fragments(cur: Cursor, sign_frag_only: set) -> Err:
PEP-8 rule: [leave two blank lines between functions](https://peps.python.org/pep-0008/#blank-lines).

2022-07-01 13:49 UTC, matthiasblum commented on pronto/templates/index.html
> +                </a>
Automatic formatting?

2022-07-01 13:49 UTC, matthiasblum commented on pronto/api/checks/go_terms.py
> +        """.format(prog3)
Insecure, use bind variables: https://cx-oracle.readthedocs.io/en/latest/user_guide/bind.html.

2022-07-01 13:49 UTC, matthiasblum commented on pronto/api/checks/entries.py
> +        """, list(sign_frag_only)
This won't work. In `cx_Oracle,` variables are not bound with `%s` (like in `psycopg2` and `MySQLdb`) but with `:<id>` where `<id>` can be a number or a name. See https://github.com/ProteinsWebTeam/pronto/blob/master/pronto/api/annotation.py#L191-L199 for an example.

2022-07-01 13:49 UTC, matthiasblum commented on pronto/api/checks/entries.py
> +def get_signatures(pg_url: str) -> Err:
The function is supposed to return an `Err` which is defined a list of tuples, where each tuple is composed of either two strings or one string and `None`. Currently, the function returns a set of strings. It would be better to return a list of strings (we don't actually a set, as there are not duplicated signatures).

Also, maybe rename the function to give it a name closer to what the function does, e.g. `get_frags_only_signatures()` .

2022-07-01 13:49 UTC, matthiasblum commented on pronto/api/checks/entries.py
> +        yield "fragment_matches", item
PEP-8: a file you should end with a new line character.

2022-07-05 11:14 UTC, matthiasblum approved these changes
Looks good! :+1: 

Feel free to merge.

2022-07-05 14:43 UTC, merged