Ibu 10219
ProteinsWebTeam/pronto pull request #58
Opened 2023-01-04 13:32 UTC by typhainepl

This is a first attempt at sorting columns.
Any feedback or improvements is welcome ;)

2023-01-10 15:57 UTC, matthiasblum requested changes
Well done, thank you! :)

I've suggested a few improvements, briefly:

- it's better for the API to accept two different query parameters (one for the column to sort by, another for the sorting order). It avoids having to allow all the possible combinations (`accession asc`, `accession desc`, `proteins asc`, `proteins desc`). That's not really a problem when we only have two sortable columns, but if we have six...
- the code for the column headers can be simplified: instead of having three icon buttons (one visible, two hidden), we can have one icon only and update its class based on user actions
- the JS code can also be simplified to avoid code duplication. Assuming column headers have` data-sort-by` and `data-sort-order` attributes, you could do something like this:
  - Get all headers of sortable columns (`document.querySelectorAll('th[data-sort-by]')`)
  - For each header, add event listener on `click` that, when triggered:
    - get the sortBy and sortOrder values (for the clicked column)
    - build a URL with the query parameters to use for the new ordering
    - update the sort icon
    - reset the sort icon of the other column
    - call `getSignatures()`

2023-01-10 15:57 UTC, matthiasblum commented on pronto/api/database.py
> +        )
Better to split this parameter in two:
- `sort_by` that accepts `accession` and `proteins`
- `sort_order` that accepts `asc` and `desc`

2023-01-10 15:57 UTC, matthiasblum commented on pronto/api/database.py
> +    results=sort_columns(results, sort_filter)
The first sort is now obsolete because whatever the result is, another sort occurs just after.
The second sort can be greatly simplified if using two query parameters `sort_by` and `sort_order`:

```py
results.sort(key=lambda x: x[sort_col], reverse=sort_order == "desc")
```

2023-01-10 15:57 UTC, matthiasblum commented on pronto/static/js/database/unintegrated.js
> +});
Try to avoid duplicating code for the two sortable columns.

2023-01-10 15:57 UTC, matthiasblum commented on pronto/templates/database/unintegrated.html
> +                                </th>
I am not what the `inline sort` of the `div` is for.

Code could be simplified for example like this (for the Accession column)

```html
<th class="nowrap" data-sort-by="accession" data-sort-order="asc">
  Accession
  <i class="up sort button icon"></i>
</th>
```

- The `nowrap` class (`th` element) prevent the icon to wrap to a separate line
- `data-sort-by` and `data-sort-order` keep the sorting information
- only one icon, whose class will be updated when clicked on

2023-01-17 16:39 UTC, matthiasblum requested changes
Well done, thanks.

Besides the ▼/▲ confusion and the `var` keyword to replace by `let`, all my comments are suggestions and it's up to you to implement them or not. ;)

2023-01-17 16:39 UTC, matthiasblum commented on pronto/static/js/database/unintegrated.js
> +    col_headers.forEach(node => {
There are no standard practice that dictates whether we should use camel case (`colHeaders`) or snake case (`col_headers`) in JavaScript, but as I've already started using camel case in Pronto, better keep using it.

2023-01-17 16:39 UTC, matthiasblum commented on pronto/static/js/database/unintegrated.js
> +                otherEl = "accession"
This will work fine here, because we only have two columns to sort by, but it would be more complicated if we had more.

In this case, you could loop over all column headers, and "reset" the ones that are _not_ the current column header, e.g.:

```js
col_headers.forEach((otherNode) => {
  if (otherNode !== node) {
    // do something with otherNode
  }
});
```

2023-01-17 16:39 UTC, matthiasblum commented on pronto/static/js/database/unintegrated.js
> +                document.getElementById(`${sortBy}-btn`).className = "button icon sort up";
When sorting in descending order , the icon should be ▼so `button icon sort down`. The `up` class is for ▲ (ascending order).

Also, it's not necessary to assign an `id` to the icon element: we can get it with `node.querySelector('i')`.

2023-01-17 16:39 UTC, matthiasblum commented on pronto/templates/database/unintegrated.html
> +                                    <i class="button icon sort before" id="proteins-btn"></i>
The `before` class does nothing and can be safely removed.

2023-01-18 10:25 UTC, typhainepl commented on pronto/api/database.py
> +                        f"message": "Accepted values are: " "accession, proteins",
these automatic quotes...

2023-01-18 10:25 UTC, typhainepl commented on pronto/static/js/database/unintegrated.js
> +    col_headers.forEach(node => {
good point

2023-01-18 10:26 UTC, typhainepl commented on pronto/static/js/database/unintegrated.js
> +            var sortOrder = node.getAttribute("data-sort-order")
I didn't know, thanks for the tip.
How does the code make the link between the dash-separated attribute in the HTML code and the camel-case called in the dataset?

2023-01-18 10:27 UTC, typhainepl commented on pronto/static/js/database/unintegrated.js
> +                otherEl = "accession"
I wasn't sure how to handle the case of more than two columns. Thanks for the tip.

2023-01-18 10:27 UTC, typhainepl commented on pronto/static/js/database/unintegrated.js
> +                document.getElementById(`${sortBy}-btn`).className = "button icon sort up";
done

2023-01-18 10:28 UTC, typhainepl commented on pronto/templates/database/unintegrated.html
> +                                    <i class="button icon sort before" id="proteins-btn"></i>
Yes the "before" is useful to know that the column can be sorted.

2023-01-23 09:24 UTC, matthiasblum commented on pronto/static/js/database/unintegrated.js
> +            var sortOrder = node.getAttribute("data-sort-order")
> How does the code make the link between the dash-separated attribute in the HTML code and the camel-case called in the dataset?
I believe it's part of the JS implementation of the `dataset` attribute. The name convention is described at https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset#name_conversion.

2023-01-23 10:02 UTC, matthiasblum approved these changes
Looks good. Thank you. :+1: 
Only one thing to change, but it's very small, so I'll do it before merging.

2023-01-23 10:04 UTC, merged