PANTHER GO
ProteinsWebTeam/pronto pull request #59
Opened 2023-01-27 16:39 UTC by typhainepl

Example of signatures used: 
signatures/PTHR23315/PTHR12120/PR01969/go/#!

2023-02-07 20:08 UTC, matthiasblum reviewed
What is the aim of this PR? Because I am not sure I understand it.

The new value presented for a given PANTHER family is the number of its subfamilies associated with a given GO term, and not a number of proteins. I find this slightly confusing.

2023-04-13 10:19 UTC, typhainepl commented
@matthiasblum up to date databases for testing are IPDEV and intdev.
Shouldn't be deployed before pyinterprod pipeline is ran again.

2023-05-25 10:06 UTC, typhainepl commented on pronto/api/signatures/go.py
> +            s = term["signatures"][pth_fam] = [set(), set(), set()]
I've added a check, but open to suggestions

2023-05-25 14:02 UTC, matthiasblum requested changes
Please find comments below. 

The only issue I have is the use of string interpolations in SQL statements instead of using bind variables, because this is a security issue.

There are a few things where performance could become an issue, but that would be for PANTHER families matching a lot of proteins.

2023-05-30 15:44 UTC, typhainepl commented on pronto/static/js/signatures/go.js
> +                        <th class="collapsing center aligned" id="first-ignored">UNI</th>
that doesn't work, it still picks the attributes of the first child...

2023-05-30 17:53 UTC, matthiasblum commented on pronto/static/js/signatures/go.js
> +                        <th class="collapsing center aligned" id="first-ignored">UNI</th>
Hmm... need to use the infamous `!important`:

Replace

https://github.com/ProteinsWebTeam/pronto/blob/4b9beb5c374b15af12b6675df82b48a1ed3412fe/pronto/static/js/signatures/go.js#L44

by

```js
                        <th class="collapsing center aligned normal">UNI</th>
```

Add the following in `pronto/static/css/go.css`:

```css
.ui.table > thead > tr > th.normal {
    border-left: 1px solid rgba(34, 36, 38, 0.1) !important;
    background: #F9FAFB !important;
    color: rgba(0, 0, 0, 0.87) !important;
    font-weight: bold !important;
}
```

Refresh

![image](https://github.com/ProteinsWebTeam/pronto/assets/2097501/5e574b38-e479-4bb6-9651-3eb39e6d4da4)

2023-05-31 09:00 UTC, typhainepl commented on pronto/static/js/signatures/go.js
> +                        <th class="collapsing center aligned" id="first-ignored">UNI</th>
That worked, thanks!

2023-05-31 16:24 UTC, matthiasblum requested changes
Looks better. There are still a few things to change, especially regarding bind variables. But we're almost there! :muscle:

2023-05-31 16:24 UTC, matthiasblum commented on pronto/api/signatures/go.py
> +    return go_details
PEP-8 & bind variables:

```suggestion
def get_go_details(term_ids: list[str], pg_cur) -> list[dict]:
    details = []

    binds = ["%s" for _ in term_ids]
    pg_cur.execute(
        f"""
        SELECT t.id, t.name, t.category
        FROM term t
        WHERE t.id IN ({','.join(binds)})
        """,
        term_ids
    )

    columns = ("id", "name", "aspect")
    for row in pg_cur.fetchall():
        details.append(dict(zip(columns, row)))

    return details

```

2023-05-31 16:24 UTC, matthiasblum commented on pronto/api/signatures/go.py
> +    return terms
Using `range()` and modified version of `get_go_details()`:

```suggestion
    go_terms = list(go_terms)
    for i in range(0, len(go_terms), 100):
        subset = go_terms[i:i+100]

        for term in get_go_details(subset, pg_cur):
            terms[term["id"]].update(term)

    return terms
```

2023-06-01 11:23 UTC, typhainepl commented
@matthiasblum I applied the suggested changes

2023-06-01 11:52 UTC, merged