Cabs updates
ProteinsWebTeam/pronto pull request #71
Opened 2023-06-19 17:10 UTC by typhainepl

This PR contains the following changes:

- automatic replacement of white space after start html tags and before end html tags
- automatic addition of <p></p> tags when creating a new CAB or editing an existing CAB that doesn't have any tag.
- resolve sanity check issue with uppercase exception not being saved

2023-06-19 23:19 UTC, matthiasblum requested changes
In good shape. Just a few things to address.

2023-06-19 23:19 UTC, matthiasblum commented on pronto/api/annotation.py
> +        return text
This function should be merged with `wrap()`:

- if `self.text` contains the pattern `r"(<(?:p|ul|ol|li)>)"`, then run the code currently in `wrap()`
- otherwise, run this code

Finally, it's not possible to have a line break inside paragraphs, e.g.

```
A

B
C

D
```

becomes


```html
<p>A</p>

<p>B</p>

<p>C</p>

<p>D</p>
```

It's perfectly fine if curators don't need them, but you may ask them.

2023-06-19 23:19 UTC, matthiasblum commented on pronto/api/checks/annotations.py
> +    prog = re.compile(r"^\s*(?:<p>)?\s*([a-z][A-Za-z]+)\s+")
- Replacing `[a-z][A-Za-z]+` by `[a-z][A-Za-z]*`: the former won't match _a family_
- I assume the `\s+` is to find the end of the first word. In this case, [`\b`](https://docs.python.org/3/library/re.html#index-28) might be a better choice.

```suggestion
    prog = re.compile(r"^\s*(?:<p>)?\s*([a-z][A-Za-z]*)\b")
```

2023-06-20 10:03 UTC, typhainepl commented
feedback have been addressed

2023-06-20 10:45 UTC, merged

2023-06-20 10:45 UTC, matthiasblum commented
Thanks. Merging.