Resolve comment issue in unchecked entries and add list numbering
ProteinsWebTeam/pronto pull request #73
Opened 2023-06-29 16:12 UTC by typhainepl

This PR does the following:
Resolve the comment issue in the Unchecked entries page
 Add list numbering for Sanity check and Recent entries pages

2023-07-03 12:57 UTC, matthiasblum requested changes
Thank you.

The row number looks good, I just suggested to make the column collapsing so it takes up as little space as possible.

The comments on the _Unchecked entries_ page look much better. I would suggest two changes:

- refactor the `/api/entry/.../comments/` endpoint to allow to get the comments for the entry, but also the comments for the signatures integrated in the entry (this allows the get all comments in one query instead of two)
- refactor the popups initialisation to use `initPopups()` in `ui.comments`.

2023-07-03 12:57 UTC, matthiasblum commented on pronto/templates/index.html
> +                    <th></th>
```suggestion
                    <th class="collapsing">#</th>
```

2023-07-03 12:57 UTC, matthiasblum commented on pronto/static/js/index.js
>      };
I refactored [`ui.comments.initPopups()`](https://github.com/ProteinsWebTeam/pronto/blob/8bb41e5f15ab1e5f35353e03c1135c62f781b7fd/pronto/static/js/ui/comments.js#L20) so it can be used here instead of reimplementing another `initPopups()`.

You can use it as such:

```js
initPopups({
    element: tab,
    buildUrl: (accession) => `/api/entry/{accession}/comments?signatures`,
    createPopup: (payload) => {
         let html = '';
         // Build HTML content of the pop-up
         return html;
    }
});
```

The `createPopup` argument is a function that takes one argument (the API payload) and must return the HTLM of the pop-up. A basic implementation is available in `ui.comments`:

https://github.com/ProteinsWebTeam/pronto/blob/8bb41e5f15ab1e5f35353e03c1135c62f781b7fd/pronto/static/js/ui/comments.js#L41-L56

2023-07-09 12:02 UTC, matthiasblum approved these changes
Looks good.

Two comments regarding the retrieval and display of both entry and signatures comments:

- with the current implementation, the entry's comments will always be first, even if a signature's comment is more recent.
- using the default `createPopup` will display all comments, but curators won't know whether the comment is for an entry or a signature.

If you're fine with this, feel free to merge. Otherwise, you will need to make some changes.

2023-07-09 20:43 UTC, typhainepl commented on pronto/api/entry/comments.py
> +            "accession": row[5],
the results accession can be a signature or the entry used in the API call, hence why I added the entry_ac in the SQL request and replaced the accession by row[5].

2023-07-09 20:45 UTC, typhainepl commented
- with the current implementation, the entry's comments will always be first, even if a signature's comment is more recent.
=> I think it is fine, we mainly have comments for signatures anyway

- using the default createPopup will display all comments, but curators won't know whether the comment is for an entry or a signature. 
=> I've updated the function to also display the accession, this way we now to which entry or signature it refers to.

2023-07-09 21:34 UTC, matthiasblum commented on pronto/api/entry/comments.py
> +            "accession": row[5],
There is only one comment table being queries at this point: `ENTRY_COMMENT`:

https://github.com/ProteinsWebTeam/pronto/blob/1a74fed1a3aa6705de899ca3465367a3b92d5ca0/pronto/api/entry/comments.py#L31-L39

Therefore, only the entry accession can be returned.

2023-07-10 08:17 UTC, typhainepl commented on pronto/api/entry/comments.py
> +            "accession": row[5],
You are right, my apologies!

2023-07-10 10:08 UTC, typhainepl commented
Let me know if you are happy with the latest changes

2023-07-10 13:53 UTC, merged