add signatures to table and no comment option for Recent entries
ProteinsWebTeam/pronto pull request #77
Opened 2023-10-05 13:27 UTC by typhainepl

In Recent entries, I have added a new column displaying the signatures integrated in the entry to the table and an option no hide entries with comments.

2023-10-05 21:20 UTC, matthiasblum requested changes
Looks good. Made a few minor suggestions/comments.

2023-10-05 21:20 UTC, matthiasblum commented on pronto/api/entries.py
> +          NVL(U.NAME, A.DBUSER), E.CHECKED, NVL(EC.CNT, 0), NVL(MC.CNT, 0), SIGN.SI
PEP 8 formatting:

```suggestion
          NVL(U.NAME, A.DBUSER), E.CHECKED, NVL(EC.CNT, 0), NVL(MC.CNT, 0), 
          SIGN.SI
```

2023-10-05 21:20 UTC, matthiasblum commented on pronto/api/entries.py
> +            GROUP BY ENTRY_AC
Indentation:

```suggestion
          SELECT ENTRY_AC, 
          LISTAGG(METHOD_AC, ', ') WITHIN GROUP (ORDER BY METHOD_AC) si
          FROM INTERPRO.ENTRY2METHOD E2M
          GROUP BY ENTRY_AC
```

2023-10-05 21:20 UTC, matthiasblum commented on pronto/api/entries.py
> +                "signatures": row[9],
It would be better if `signatures` was returned as an array of strings instead of a string.

2023-10-05 21:20 UTC, matthiasblum commented on pronto/static/js/index.js
> +            <td>${entry.signatures}</td>
Create link to `/signature/<accession>/` for each signature.

2023-10-09 10:24 UTC, typhainepl commented
@matthiasblum you can go ahead with the PR review.

2023-10-11 08:57 UTC, matthiasblum requested changes
Didn't review the code. 
The home page fails to load, probably because the new code expects the user to be logged in and I wasn't. 
Please fix and re-request a review.

2023-10-13 13:13 UTC, typhainepl commented
Bug is fixed @matthiasblum

2023-10-18 10:55 UTC, matthiasblum requested changes
A few issues:

- `current_user` in the payload includes the user's password. This should never be returned.
- it's only possible to filter by author when logged in. When not logged in, only the _Anyone_ option is available.
- do not use `var` in JavaScript, but `const` or `let`.

You can simplify the by-author filter by only showing the names of curators who recently created at least one entry. If a curator is interested in their entries only, they don't need a _Me_ option, they can use their name. And if someone hasn't recently created any entry, I don't think we need to add their name to the list of options.

It's simple to get the sorted list of unique curator names from the API results:

```js
const curators = [...new Set(data.results.map((e => e.user)))].sort();
```

From there, you can build the `select` element.

2023-10-18 10:55 UTC, matthiasblum commented on pronto/api/entries.py
> +          E.CHECKED, NVL(EC.CNT, 0), NVL(MC.CNT, 0), SIGN.SI
PEP-8 and renaming aliases

```suggestion
          E.ENTRY_AC, E.ENTRY_TYPE, E.SHORT_NAME, A.TIMESTAMP, 
          NVL(U.NAME, A.DBUSER), E.CHECKED, NVL(EC.CNT, 0), NVL(MC.CNT, 0), 
          EM.ACCESSIONS
```

2023-10-18 10:55 UTC, matthiasblum commented on pronto/api/entries.py
> +        ) SIGN ON SIGN.ENTRY_AC=E.ENTRY_AC
Rename aliases, and do not sort accessions in SQL (done directly in Python):

```suggestion
        LEFT OUTER JOIN (
          SELECT ENTRY_AC, LISTAGG(METHOD_AC, ',') ACCESSIONS
          FROM INTERPRO.ENTRY2METHOD E2M
          GROUP BY ENTRY_AC
        ) EM ON E.ENTRY_AC = EM.ENTRY_AC
```

2023-10-18 10:55 UTC, matthiasblum commented on pronto/api/entries.py
> +                "signatures": row[8].split(',') if row[8] else None,
Keep the type of `signatures` consistent (always a `list`), and sort accessions if any:

```suggestion
                "signatures": sorted(row[8].split(',')) if row[8] else [],
```

2023-10-18 15:03 UTC, matthiasblum approved these changes
Looks good. Thanks.

I made a few suggestions, none critical, but please include them. Then, feel free to merge and re-deploy. :rocket:

2023-10-18 15:03 UTC, matthiasblum commented on pronto/static/js/index.js
> +    var dynamicSelect = document.getElementById('curators');
`var` -> `const`:

```suggestion
    const dynamicSelect = document.getElementById('curators');
```

2023-10-18 15:03 UTC, matthiasblum commented on pronto/static/js/index.js
> +    const curators = new Set(data.results.map((e => e.user)));
Sort the curators by name:

```suggestion
    const curators = [...new Set(data.results.map((e => e.user)))].sort();
```

2023-10-18 15:18 UTC, merged