adding funfam GO terms
ProteinsWebTeam/pronto pull request #82
Opened 2023-12-11 18:16 UTC by typhainepl

This is the PR to add Funfam GO terms to the GO terms tab in Pronto.
When clicking on the number, I've tried to reuse the module created for PANTHER GO terms, let me know if you think it would be better to separate the 2 completely.

2023-12-12 16:01 UTC, matthiasblum commented
Before reviewing the pull request, can we assess if we really need it?

In June, a pull request (#59) was introduced, enabling curators to access the number of proteins matched by PANTHER subfamilies associated with specific GO terms. After looking at the server logs, it appears that this feature has been used a mere four times since its implementation in June. I am a bit hesitant to incorporate a feature of similar nature unless there is a demonstrated need for it.

2023-12-14 18:16 UTC, matthiasblum requested changes
In decent shape, thanks. There are a few inline comments/suggestions.

There is an issue, though: the table now shows some GO terms that shouldn't be there. 

`G3DSA:1.10.10.1210` (live instance of Pronto):

![image](https://github.com/ProteinsWebTeam/pronto/assets/2097501/359bff34-6f90-4b4a-af33-e70da2b4b44c)

`G3DSA:1.10.10.1210` (local instance, using the same databases as the live instance):

![image](https://github.com/ProteinsWebTeam/pronto/assets/2097501/52588346-12c5-47a0-b967-ae4ff3ad753b)

There are 10 additional GO terms, and the number of proteins of some GO terms is different (e.g. ` GO:0000122`: 323 -> 416).

2023-12-14 18:16 UTC, matthiasblum commented on pronto/static/js/signatures/go.js
> +                            if (acc.search('PTHR') == 0) {
```suggestion
                            if (acc.startsWith('PTHR')) {
```

2023-12-14 18:16 UTC, matthiasblum commented on pronto/static/js/signatures/go.js
> +                            else if (acc.search('G3DSA') == 0) {
```suggestion
                            else if (acc.startsWith('G3DSA')) {
```

2023-12-15 14:51 UTC, typhainepl commented on pronto/api/signature.py
> +        return get_funfam_go(accession, term_id)
Thanks for pointing out the `startwith` function; I didn't know about it! I'll make the required changes

2023-12-15 16:41 UTC, typhainepl commented
> In decent shape, thanks. There are a few inline comments/suggestions.
> 
> There is an issue, though: the table now shows some GO terms that shouldn't be there.
> 
> `G3DSA:1.10.10.1210` (live instance of Pronto):
> 
> ![image](https://private-user-images.githubusercontent.com/2097501/290616917-359bff34-6f90-4b4a-af33-e70da2b4b44c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTg3MzksIm5iZiI6MTcwMjY1ODQzOSwicGF0aCI6Ii8yMDk3NTAxLzI5MDYxNjkxNy0zNTliZmYzNC02ZjkwLTRiNGEtYWYzMy1lNzBkYTJiNGI0NGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTY0MDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRjODE4NDg0MGZlMmFiZjc5NDUwMmNlMGNiY2JlNDNiZjYyZWU5MTI4MmQzOGM1NGNjNDJiOTU5ZTUwYWY2OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lYD98HuegIulreeZ4i11-nRCkpMlDQEPsNzuZH6cAnQ)
> 
> `G3DSA:1.10.10.1210` (local instance, using the same databases as the live instance):
> 
> ![image](https://private-user-images.githubusercontent.com/2097501/290617091-52588346-12c5-47a0-b967-ae4ff3ad753b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTg3MzksIm5iZiI6MTcwMjY1ODQzOSwicGF0aCI6Ii8yMDk3NTAxLzI5MDYxNzA5MS01MjU4ODM0Ni0xMmM1LTQ3YTAtYjk2Ny1hZTRmZjNhZDc1M2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMTY0MDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWUwOTlkZjdjNzA1ZDUyZjNiNTdhNDNlYjAxZDMzNGZiZjM4NWYxMDhiYzI2NTY2NWJmZTI4YjVmZDI3ZjBjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.O5MqaJ8DI2ey2m8ZMo0AQOKytbfzxNsEtAosVxUVN30)
> 
> There are 10 additional GO terms, and the number of proteins of some GO terms is different (e.g. ` GO:0000122`: 323 -> 416).

Well spotted! I've solved the problem.

2023-12-15 16:43 UTC, typhainepl commented on pronto/api/signature.py
> +        "count": count_prot,
No, that's correct. The goal is to see how many proteins are annotated with this GO term by the Funfam compared to the total number of proteins matched by the Gene3D signature.

2024-01-05 14:21 UTC, matthiasblum approved these changes
Looks good, thanks. I've added two minor suggestions. Please incorporate them, then feel free to merge.

2024-01-05 14:21 UTC, matthiasblum commented on pronto/api/signature.py
> +        return jsonify(), 404
Add an error with some details, and use the HTTP status code `400` (invalid request) instead of `404` (not found):

```suggestion
        return jsonify({
            "error": {
                "title": "Invalid signature",
                "message": "Only CATH-Gene3D and PANTHER signatures "
                           "have subfamilies."
            }
        }), 400
```

2024-01-05 14:21 UTC, matthiasblum commented on pronto/api/signature.py
> +
Two blank lines between functions (PEP-8 recommendation):

```suggestion


```

2024-01-05 16:21 UTC, merged