[IBU-10663] Get GO taxon constraints
ProteinsWebTeam/pronto pull request #83
Opened 2023-12-12 08:21 UTC by laisecf

2024-01-03 17:40 UTC, matthiasblum requested changes
Needs some work. Please see comments/suggestions.

2024-01-03 17:40 UTC, matthiasblum commented on pronto/api/signatures/proteins.py
There is an issue with the way the filtering is implemented on the `/api/signatures/.../proteins` endpoint.

:car: :lock: :seat:  Fasten your seatbelt, it's going to be technical! :rocket: :wrench: 

If a GO term is passed to the API, the default behaviour is to return proteins that have been assigned this GO term. However there are different ways GO terms can be assigned to proteins. If an annotation (GO-protein) is generated automatically, is it called an Inferred from Electronic Annotation (IEA). In Pronto, we ignore IEAs because we want to focus on reviewed/manual annotations.

If an InterPro curator assigns a GO term an entry, all proteins matched by this entry will be assign the GO term as well. But, it is an IEA (because not all term-protein are reviewed).

Let's take an example with `IPR011812` and `GO:0009252`.
`IPR011812` matches three signatures: `MF_00766`, `PTHR30400`, and `TIGR02070`.
How many proteins are (currently) matched by these signatures? **13,465** (`/api/signatures/MF_00766/PTHR30400/TIGR02070/proteins/`).
And how many proteins are (currently) matched by these signatures _and also_ manually assigned `GO:0009252`? **Only 1** (`/api/signatures/MF_00766/PTHR30400/TIGR02070/proteins/?go=GO:0009252`).

Now, we want to be able to retrieve proteins that violate a GO term's taxon constraints. That's why you added the `tax-constraints` parameter:

https://github.com/ProteinsWebTeam/pronto/blob/562aeefe16e6dc053fdc33d4cab8371cc90a18e5/pronto/api/signatures/proteins.py#L30

And what does the API returns?
One protein (`/api/signatures/MF_00766/PTHR30400/TIGR02070/proteins/?go=GO:0009252&tax-constraints`).

That's because we still filter manual term-protein annotations:

https://github.com/ProteinsWebTeam/pronto/blob/562aeefe16e6dc053fdc33d4cab8371cc90a18e5/pronto/api/signatures/proteins.py#L205-L215

I think it'd be better to only use the `go` parameter when we want manual annotations, and transform the "boolean" `tax-constraints` into a parameter that expects a value, such as `violate-go=GO:0009252`.

2024-01-04 15:51 UTC, laisecf commented on pronto/api/entry/go.py
> +                violation_reviewed += 1
I will make a small change here, check if you agree:
In the case of the "only_in_taxon" relationship having more than one taxon per go_term, it would be a logical OR, so we cannot consider `is_ok = False` before checking all possible only_in constraints for this go term, right?

2024-01-04 17:07 UTC, laisecf commented on pronto/api/entry/go.py
> +    taxon_constraints = pg_cur.fetchall()
I will remove the violations count from here because the `only_in_taxon` (will be just one violation per set of `only in`). Maybe we need to change in database because I now I notice its probably better only_in be a set (not one per row).

2024-01-05 17:07 UTC, laisecf commented on pronto/api/entry/go.py
> +                violation_reviewed += 1
I keep the internal counter with a "warning" comment about the cases with more than one only_in (will increase the violation without checking all only_in). 
The general counter (the most important for us) is counting correctly (the variable only_in_ok is checking this).

2024-01-05 19:11 UTC, matthiasblum commented on pronto/api/entry/go.py
> +                violation_reviewed += 1
Good point! I'm resolving this conversation and will suggest changes in another.

2024-01-05 21:54 UTC, matthiasblum requested changes
Almost there!

2024-01-05 21:54 UTC, matthiasblum commented on pronto/api/signatures/proteins.py
> +                }), 400
Changes:

1. Get GO term's name and return error if it exists
2. If there are not taxon constraints for the GO terms, it's not necessary to return an error: no protein will be returned
3. Directly add the taxon constraints to the global filter

```suggestion
        violate_term_name = None
        if violate_term_id is not None:
            cur.execute("SELECT name FROM term WHERE ID = %s",
                        [violate_term_id])
            row = cur.fetchone()
            if row:
                violate_term_name, = row
            else:
                cur.close()
                con.close()
                return jsonify({
                    "error": {
                        "title": "Bad Request (invalid GO term)",
                        "message": f"No GO term with ID {violate_term_id}."
                    }
                }), 400

            only_in = []
            only_in_params = []
            tax_filters = []
            tax_params = []
            cur.execute(
                f"""
                SELECT g.relationship, t.left_number, t.right_number
                FROM go2constraints g
                INNER JOIN taxon t ON g.taxon = t.id
                WHERE go_id = %s
                """,
                [violate_term_id]
            )
            for rel_type, left_num, right_num in cur.fetchall():
                if rel_type == "only_in_taxon":
                    only_in.append("taxon_left_num NOT BETWEEN %s AND %s")
                    only_in_params += [left_num, right_num]
                else:
                    tax_filters.append("taxon_left_num BETWEEN %s AND %s")
                    tax_params += [left_num, right_num]

            if only_in:
                tax_filters.append(f"({' AND '.join(only_in)})")
                tax_params += only_in_params

            if tax_filters:
                filters.append(f"({' OR '.join(tax_filters)})")
                params += tax_params
```

2024-01-05 21:54 UTC, matthiasblum commented on pronto/api/signatures/proteins.py
> +
Not necessary with my suggestion above. Also this might be less efficient since it involves an extra subquery to `signature2protein`.

```suggestion
```

2024-01-05 21:54 UTC, matthiasblum commented on pronto/api/signatures/proteins.py
> +            "go": f"{go_id}: {term_name}" if term_name else None,
Again, we want to have a clear separation between filters, so we return an extra `violate-go` property:

```suggestion
            "go": f"{term_id}: {term_name}" if term_name else None,
            "violate-go": (f"{violate_term_id}: {violate_term_name}"
                           if violate_term_name else None),
```

2024-01-08 09:06 UTC, laisecf commented on pronto/api/entry/go.py
> +            "violations": {
good idea, will make sense this way

2024-01-08 09:09 UTC, laisecf commented on pronto/api/entry/go.py
> +            is_ok = False
You're right! I need to think more in the edge cases 😞 Thank you! o/

2024-01-08 15:20 UTC, matthiasblum approved these changes
LGTM. Well done! :+1:

2024-01-08 15:21 UTC, merged