[IBU-10730] Update references when deleting annotations
ProteinsWebTeam/pronto pull request #84
Opened 2024-01-02 11:14 UTC by laisecf

2024-01-03 19:09 UTC, matthiasblum requested changes
In good shape, but requires some work. The `update_references` function updates one entry after the other. This is not a problem for production pipelines, but we should avoid doing many small queries/updates in the context of a web application (we want things to be updated as fast as possible!).

The function could take only two arguments:

1. the cursor
2. the annotation ID to be deleted

I'm going to describe a way to do this with annotation ID `AB12133`.

First, we get the references that entries being described with `AB12133` have:

```sql
SELECT ENTRY_AC, PUB_ID
FROM INTERPRO.ENTRY2PUB
WHERE ENTRY_AC IN (
    SELECT ENTRY_AC
    FROM INTERPRO.ENTRY2COMMON
    WHERE ANN_ID = 'AB12133'
);
```

```python
entry2pub = {}
for entry_acc, pub_id in cur.fetchall():
    try:
        entry2pub[entry_acc].add(pub_id)
    except KeyError:
        entry2pub[entry_acc] = {pub_id}
```

And we do the same for supplementary references:

```sql
SELECT ENTRY_AC, PUB_ID
FROM INTERPRO.SUPPLEMENTARY_REF
WHERE ENTRY_AC IN (
    SELECT ENTRY_AC
    FROM INTERPRO.ENTRY2COMMON
    WHERE ANN_ID = 'AB12133'
);
```

```python
entry2suppl = {}
for entry_acc, pub_id in cur.fetchall():
    try:
        entry2suppl[entry_acc].add(pub_id)
    except KeyError:
        entry2suppl[entry_acc] = {pub_id}
```

Then, we get all annotations for the same entries (but we exclude `AB12133` since it's going to be deleted):

```sql
SELECT CA.ANN_ID, CA.TEXT, EC.ENTRY_AC
FROM INTERPRO.COMMON_ANNOTATION CA
INNER JOIN ENTRY2COMMON EC on CA.ANN_ID = EC.ANN_ID
WHERE CA.ANN_ID != 'AB12133'
 AND EC.ENTRY_AC IN (
    SELECT ENTRY_AC
    FROM INTERPRO.ENTRY2COMMON
    WHERE ANN_ID = 'AB12133'
);
```

| ANN\_ID | TEXT | ENTRY\_AC |
| :--- | :--- | :--- |
| AB00254 | ... | IPR016391 |
| AB50158 | ... | IPR047312 |

```python
annotations = {}
for ann_id, text, entry_acc in cur.fetchall():
    try:
        annotations[ann_id]["entries"].append(entry_acc)
    except KeyError:
        annotations[ann_id] = {
            "text": text,
            "entries": [entry_acc]
        }
```

Now we can extract references from annotations. Since we have a dictionary of annotations, we will parse the text of each annotation only once, even if it is assigned to many entries.

```python
prog_ref = re.compile(r"\[cite:(PUB\d+)\]", re.I)
for ann in annotations.values():
    pubs = set()
    for m in prog_ref.finditer(ann["text"]):
        pubs.add(m.group(1))

    for entry_acc in ann["entries"]:
        try:
            entry2pub[entry_acc] -= pubs
        except KeyError:
            continue
```

For each annotation, we build a set of references (found in this annotation). Then we substract these references for each entry that has the annotation. So in the end, the references in `entry2pub` are the one that were not found in annotations that are not `AB12133`, i.e. the references to remove from the `ENTRY2PUB` table.

We can create the list of rows to remove from `ENTRY2PUB`, and to insert in `SUPPLEMENTARY_REF` (if not already there):

```python
del_entry2pub = []
new_suppl = []
for entry_acc, pubs in entry2pub.items():
    for pub_id in pubs:
        del_entry2pub.append((entry_acc, pub_id))

        if pub_id not in entry2suppl.get(entry_acc, []):
            new_suppl.append((entry_acc, pub_id))
```

Finally, we can insert/delete rows:

```python
if del_entry2pub:
    cur.executemany(
        """
        DELETE FROM INTERPRO.ENTRY2PUB
        WHERE ENTRY_AC = :1 AND PUB_ID = :2
        """,
        del_entry2pub
    )

if new_suppl:
    cur.executemany(
        """
        INSERT INTO INTERPRO.SUPPLEMENTARY_REF
        VALUES (:1, :2)
        """,
        new_suppl
    )
```

Your `update_references` function could be renamed to `track_references` and it would return `del_entry2pub` and `new_suppl`. The `INSERT` and `DELETE` queries would be done in the `try/except` block.

2024-01-04 11:25 UTC, laisecf commented
> In good shape, but requires some work. The `update_references` function updates one entry after the other. This is not a problem for production pipelines, but we should avoid doing many small queries/updates in the context of a web application (we want things to be updated as fast as possible!).
> 
> The function could take only two arguments:
> 
> 1. the cursor
> 2. the annotation ID to be deleted
> 
> I'm going to describe a way to do this with annotation ID `AB12133`.
> 
> First, we get the references that entries being described with `AB12133` have:
> 
> ```sql
> SELECT ENTRY_AC, PUB_ID
> FROM INTERPRO.ENTRY2PUB
> WHERE ENTRY_AC IN (
>     SELECT ENTRY_AC
>     FROM INTERPRO.ENTRY2COMMON
>     WHERE ANN_ID = 'AB12133'
> );
> ```
> 
> ```python
> entry2pub = {}
> for entry_acc, pub_id in cur.fetchall():
>     try:
>         entry2pub[entry_acc].add(pub_id)
>     except KeyError:
>         entry2pub[entry_acc] = {pub_id}
> ```
> 
> And we do the same for supplementary references:
> 
> ```sql
> SELECT ENTRY_AC, PUB_ID
> FROM INTERPRO.SUPPLEMENTARY_REF
> WHERE ENTRY_AC IN (
>     SELECT ENTRY_AC
>     FROM INTERPRO.ENTRY2COMMON
>     WHERE ANN_ID = 'AB12133'
> );
> ```
> 
> ```python
> entry2suppl = {}
> for entry_acc, pub_id in cur.fetchall():
>     try:
>         entry2suppl[entry_acc].add(pub_id)
>     except KeyError:
>         entry2suppl[entry_acc] = {pub_id}
> ```
> 
> Then, we get all annotations for the same entries (but we exclude `AB12133` since it's going to be deleted):
> 
> ```sql
> SELECT CA.ANN_ID, CA.TEXT, EC.ENTRY_AC
> FROM INTERPRO.COMMON_ANNOTATION CA
> INNER JOIN ENTRY2COMMON EC on CA.ANN_ID = EC.ANN_ID
> WHERE CA.ANN_ID != 'AB12133'
>  AND EC.ENTRY_AC IN (
>     SELECT ENTRY_AC
>     FROM INTERPRO.ENTRY2COMMON
>     WHERE ANN_ID = 'AB12133'
> );
> ```
> 
> ANN_ID	TEXT	ENTRY_AC
> AB00254	...	IPR016391
> AB50158	...	IPR047312
> ```python
> annotations = {}
> for ann_id, text, entry_acc in cur.fetchall():
>     try:
>         annotations[ann_id]["entries"].append(entry_acc)
>     except KeyError:
>         annotations[ann_id] = {
>             "text": text,
>             "entries": [entry_acc]
>         }
> ```
> 
> Now we can extract references from annotations. Since we have a dictionary of annotations, we will parse the text of each annotation only once, even if it is assigned to many entries.
> 
> ```python
> prog_ref = re.compile(r"\[cite:(PUB\d+)\]", re.I)
> for ann in annotations.values():
>     pubs = set()
>     for m in prog_ref.finditer(ann["text"]):
>         pubs.add(m.group(1))
> 
>     for entry_acc in ann["entries"]:
>         try:
>             entry2pub[entry_acc] -= pubs
>         except KeyError:
>             continue
> ```
> 
> For each annotation, we build a set of references (found in this annotation). Then we substract these references for each entry that has the annotation. So in the end, the references in `entry2pub` are the one that were not found in annotations that are not `AB12133`, i.e. the references to remove from the `ENTRY2PUB` table.
> 
> We can create the list of rows to remove from `ENTRY2PUB`, and to insert in `SUPPLEMENTARY_REF` (if not already there):
> 
> ```python
> del_entry2pub = []
> new_suppl = []
> for entry_acc, pubs in entry2pub.items():
>     for pub_id in pubs:
>         del_entry2pub.append((entry_acc, pub_id))
> 
>         if pub_id not in entry2suppl.get(entry_acc, []):
>             new_suppl.append((entry_acc, pub_id))
> ```
> 
> Finally, we can insert/delete rows:
> 
> ```python
> if del_entry2pub:
>     cur.executemany(
>         """
>         DELETE FROM INTERPRO.ENTRY2PUB
>         WHERE ENTRY_AC = :1 AND PUB_ID = :2
>         """,
>         del_entry2pub
>     )
> 
> if new_suppl:
>     cur.executemany(
>         """
>         INSERT INTO INTERPRO.SUPPLEMENTARY_REF
>         VALUES (:1, :2)
>         """,
>         new_suppl
>     )
> ```
> 
> Your `update_references` function could be renamed to `track_references` and it would return `del_entry2pub` and `new_suppl`. The `INSERT` and `DELETE` queries would be done in the `try/except` block.

The logic was very good this way, much more optimized. Thank you!! o/

2024-01-04 19:53 UTC, matthiasblum requested changes
Almost there! A few things to address.

I've also made a few changes to the client (JS) to allow annotations linked to multiple entries to be deleted (that's the entire point of this PR :grin:).

2024-01-04 19:53 UTC, matthiasblum commented on pronto/api/annotation.py
> +        del_entry2pub, new_suppl = track_references(cur, ann_id)
This function needs to be called _before_ the following block:

https://github.com/ProteinsWebTeam/pronto/blob/e8b8252e330fcbf670114be1760a16fe729540c8/pronto/api/annotation.py#L894-L899

If you call it _after_, the annotation is not associated to any entry (since you delete records in `ENTRY2COMMON`), so when you execute the following query:

```sql
SELECT ENTRY_AC, PUB_ID
FROM INTERPRO.ENTRY2PUB
WHERE ENTRY_AC IN (
    SELECT ENTRY_AC
    FROM INTERPRO.ENTRY2COMMON
    WHERE ANN_ID = '...'
)
```

The nested query doesn't return anything.

2024-01-05 10:12 UTC, laisecf commented on pronto/api/annotation.py
> +        del_entry2pub, new_suppl = track_references(cur, ann_id)
My bad!!

2024-01-05 14:03 UTC, matthiasblum approved these changes
Well done. Feel free to merge.

2024-01-08 07:15 UTC, merged