Add GO term constraint information on Entry pages
ProteinsWebTeam/pronto pull request #86
Opened 2024-01-15 13:57 UTC by typhainepl

This PR displays a GO taxon constraint table in InterPro entry pages when clicking on the taxon constraint red label.
The table has 3 columns: shows the type of constraint, number of proteins with the taxon and the total number of protein matches. 

Example of entries with GO terms having a taxon constraint:
IPR003705
IPR003488 (a lot of proteins)
IPR000354

2024-01-15 17:06 UTC, matthiasblum requested changes
In good shape.

There is one small issue that causes several requests to be fired at the same time.

Also, `/api/signatures/<accessions>/proteins/?violate-go=<go-term>` returns the filters being used (`filters` object in the payload). For instance, when passing `violate-go=GO:0009236`, the API returns `GO:0009236: cobalamin biosynthetic process`. You could update [templates/signatures/proteins.html](https://github.com/ProteinsWebTeam/pronto/blob/6ffe35baa3edc5440aacd0f3f95265499403e0ae/pronto/templates/signatures/proteins.html#L74-L105) and [static/js/signatures/proteins.js](https://github.com/ProteinsWebTeam/pronto/blob/6ffe35baa3edc5440aacd0f3f95265499403e0ae/pronto/static/js/signatures/proteins.js#L117-L146) to display the GO term if `violate-go` is passed.

2024-01-17 10:41 UTC, typhainepl commented on pronto/static/js/entry/go.js
> +    for (const elem of document.querySelectorAll('[data-entry]')) {
I see, thanks for the input.

2024-01-17 10:44 UTC, typhainepl commented on pronto/static/js/entry/go.js
> +            fetch(`/api/entry/${acc}/go/${term}/`, { method: 'GET' })
Good to know. I used it because it was used in the API code. Should I remove it from there as well?

2024-01-17 11:12 UTC, matthiasblum commented on pronto/static/js/entry/go.js
> +            fetch(`/api/entry/${acc}/go/${term}/`, { method: 'GET' })
No, you can leave it for both the client and API.

2024-01-18 17:14 UTC, matthiasblum requested changes
Thanks.

I missed one thing in the previous review. :facepalm: 
It's not really an issue as it's not going to cause an error, but it's a somehow counter-intuitive way of iterating over an array (by piggy-backing on some JavaScript magic).

2024-01-18 17:14 UTC, matthiasblum commented on pronto/static/js/entry/go.js
> +                                <td>${result.constraint[item].matches.total.toLocaleString()}</td>
I missed this during the first round.

```suggestion
                    for (const constraint of result.constraint) {
                        let constType = constraint.type;
                        constType = constType.replace(/only_in_taxon/g, 'Only in');
                        constType = constType.replace(/never_in_taxon/g, 'Never in');
                        html += `<tr>
                                <td>${constType} ${constraint.taxon.name}</td>
                                <td>${constraint.matches.reviewed}</td>
                                <td>${constraint.matches.total}</td>
```

In Javascript, `for...in` is used to iterate over the properties of an object. In this case, `result.constraint` is an array so the `for...in` loop will iterate over its indices... as strings. But because arrays in JavaScript are objects, using the string representations of indices still works to access the corresponding array element.

Instead you can iterate over an array using the traditional `for...in` loop like in C:

```js
for (let index = 0; index < myArray.length; index++) {
    const item = myArray[index];
}
```

Or directly access the element using `for...of`:

```js
for (const item of myArray) {
    ...
}
```

Or using the `forEach` method:

```js
myArray.forEach((item, index) => {
    ...
});
```

2024-01-19 09:16 UTC, typhainepl commented on pronto/static/js/entry/go.js
> +                                <td>${result.constraint[item].matches.total.toLocaleString()}</td>
Thanks for the input, I've made the changes, including your previous change to define the `constType` variable.

2024-01-19 09:51 UTC, matthiasblum approved these changes
All good, thanks! :+1: 
Feel free to merge. :rocket:

2024-01-19 10:08 UTC, merged