IBU-10837: auto add ai signatures
ProteinsWebTeam/pronto pull request #92
Opened 2024-03-04 15:58 UTC by HobnobMancer

[JIRA](https://www.ebi.ac.uk/panda/jira/browse/IBU-10837) 

Add scripts to automatically integrate ai-generated signatures (name, short name and description) for member databases.

2024-03-05 15:08 UTC, HobnobMancer commented
I don't think the method for logging into pronto is correct - I will take another look early next week - but the rest of the code is code for checking.

2024-03-11 10:02 UTC, matthiasblum requested changes
Looks good. Made a few suggestions, including one that is related to security (password on the CLI).

2024-03-11 10:02 UTC, matthiasblum commented on scripts/create_ai_entries.py
> +    if (s.get(f"{args.pronto}/api/".replace("//api", "/api")).text).find('"user": Null') != -1:
If the login is successful, Flask creates a client-side cookie, so you can check whether it exists:

```suggestion
    if s.cookies.get("session") is None:
```

2024-03-11 10:28 UTC, matthiasblum commented on scripts/create_ai_entries.py
> +                if submission_response.text.find('"entries":') != -1:
Why not `submission_response.json()`?

2024-03-11 13:55 UTC, HobnobMancer commented on scripts/create_ai_entries.py
> +        args = parser.parse_args()
For testing (plus unit testing and CI if implemented), and to allow direct integration into a pipeline (if wanted), without losing the option to run as a standalone app.

2024-03-13 00:44 UTC, matthiasblum requested changes

2024-03-13 00:44 UTC, matthiasblum commented on scripts/create_ai_entries.py
> +    return any(sig_response.get(key) for key in keys)
```suggestion
    return all(sig_response.get(key) for key in keys)
```

2024-03-13 00:44 UTC, matthiasblum commented on scripts/create_ai_entries.py
> +                if len(sig_response.json()['llm_description']) > 30:
Historically, signatures had a _name_ (short name, indentifier-like, e.g. `CoV_NSP2_C`), a _description_ (e.g. `Coronavirus replicase NSP2, C-terminal`), and an _abstract_.

Unfortunately, these fields were renamed for InterPro entries, so _name_ became _short name_, _description_ became _name_, and _abstract_ became _common annotation block_ and/or _description_.

```suggestion
            if sig_response.json()['llm_name'] is not None:
                if len(sig_response.json()['llm_name']) > 30:
```

2024-03-13 00:44 UTC, matthiasblum commented on scripts/create_ai_entries.py
> +                "short_name": sig_response.json()['llm_description'],
`[llm_]description` corresponds to the _name_ of an entry.
`[llm_]name` corresponds to the _short name_ of an entry.

```suggestion
                "name": sig_response.json()['llm_description'],
                "short_name": sig_response.json()['llm_name'],
```

2024-03-13 00:44 UTC, matthiasblum commented on scripts/create_ai_entries.py
> +                'signatures': sig_acc,
* We want the entry to be checked by default (otherwise it needs to be manually checked by curators to be propagated to the data warehouse for the release).
* `signatures` takes a _list_ of accessions.

```suggestion
                'is_checked': True,
                'signatures': [sig_acc],
```

2024-03-13 00:44 UTC, matthiasblum commented on scripts/utilities.py
> +        action="store_false",
With `action="store_false"`, the value of the argument (`args.cache`) is `True` by default and `False` if `-c` or `--cache` is passed on the command line.

However, if you add `default=False`, then `args.cache` will always be `False`.
I guess you want the cache file to be used if `-c` or `--cache` is passed on the command line so you need to use `action="store_true"`.

```suggestion
        action="store_true",
```

2024-03-13 16:01 UTC, matthiasblum commented on scripts/README.md
> +                        Member databases to integrate ai generated signatures from. Default: ALL (default: ['panther', 'ncbifam', 'cathgene3d'])
```suggestion
                        Member databases to integrate ai generated signatures from. (default: all)
```

2024-03-13 16:02 UTC, matthiasblum commented on scripts/README.md
> +                        Seconds to wait between payloards to the Pronto REST API (default: 1)
```suggestion
                        Seconds to wait between payloads to the Pronto REST API (default: 0.1)
```

2024-03-13 16:15 UTC, matthiasblum commented on scripts/create_ai_entries.py
> +            if perc in sig_perc.values():
`sig_count` is never incremented. 
Also, the keys are progress milestones as strings (`10%`, `20%`), and the values are the number of signatures corresponding to the milestones. Wouldn't be more logical to reverse the key-value pairs?

2024-03-13 16:24 UTC, matthiasblum commented on scripts/utilities.py
> +        action=ValidateDatabases,
I guess that you're trying to handle database names in a case insensitive way, but it's much simpler with `type=str.lower`:

```suggestion
        type=str.lower,
```

2024-03-13 17:02 UTC, HobnobMancer commented
RE change requests on the `README` - the flag should be `--file` not `--cache` as a error file is generated not a cache, the docs and scripts have been updated as such.

2024-03-13 17:02 UTC, merged